import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";
import { headers } from "next/headers";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { LayoutClient } from "@/components/layout-client";
import { ErrorBoundary } from "@/components/error-boundary";
import { safeJsonLd } from "@/lib/utils";
import { SITE_URL, SITE_NAME, SITE_DESCRIPTION, WHATSAPP_NUMBER } from "@/lib/site-config";
import { THEME_COLOR } from "@/lib/constants";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

/** Read the per-request CSP nonce generated by middleware. */
async function getCspNonce(): Promise<string> {
  const headerList = await headers();
  return headerList.get("x-nonce") ?? "";
}

export const metadata: Metadata = {
  title: {
    default: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  keywords: [
    "ELITE VIP",
    "متجر النخبة",
    "متجر إلكتروني",
    "تطبيقات",
    "أدوات ذكاء اصطناعي",
    "خدمات رقمية",
    "تداول",
    "ربح من الإنترنت",
    "تسوق عربي",
    "منتجات",
    "VIP Shop",
    "أدوات AI",
    "تسويق رقمي",
  ],
  authors: [{ name: "Elite VIP Shop", url: SITE_URL }],
  creator: "Elite VIP Shop",
  publisher: "Elite VIP Shop",
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: SITE_URL,
  },
  icons: {
    icon: [
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    shortcut: "/icons/favicon-32.png",
    apple: "/icons/apple-touch-icon.png",
  },
  manifest: "/manifest.json",
  openGraph: {
    type: "website",
    locale: "ar_YE",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    images: [
      {
        url: "/icons/icon-512.png",
        width: 512,
        height: 512,
        alt: SITE_NAME,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    images: ["/icons/icon-512.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "shopping",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = await getCspNonce();
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="alternate" hrefLang="ar" href={`${SITE_URL}/`} />
        <meta name="theme-color" content={THEME_COLOR} />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="VIP Shop" />
        <meta name="application-name" content="VIP Shop" />
        <meta name="msapplication-TileColor" content="#d4a843" />
        <meta name="format-detection" content="telephone=yes" />
        <link rel="sitemap" type="application/xml" href="/sitemap.xml" />
        {/* Google Search Console Verification */}
        <meta name="google-site-verification" content={process.env.NEXT_PUBLIC_GSC_VERIFICATION || ""} />
        {/* Google Analytics GA4 — only rendered when measurement ID is configured */}
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
              strategy="afterInteractive"
              nonce={nonce}
            />
            <Script id="google-analytics" strategy="afterInteractive" nonce={nonce}>
              {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');`}
            </Script>
          </>
        )}
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: safeJsonLd([
              {
                "@context": "https://schema.org",
                "@type": "Organization",
                name: "Elite VIP Shop",
                url: SITE_URL,
                logo: `${SITE_URL}/icons/icon-512.png`,
                contactPoint: {
                  "@type": "ContactPoint",
                  telephone: `+${WHATSAPP_NUMBER.replace(/(\d{3})(\d{3})(\d{3})(\d{3})/, "$1-$2-$3-$4")}`,
                  contactType: "customer service",
                  availableLanguage: "Arabic",
                },
                sameAs: [`https://wa.me/${WHATSAPP_NUMBER}`],
              },
              {
                "@context": "https://schema.org",
                "@type": "WebSite",
                url: SITE_URL,
                name: SITE_NAME,
                inLanguage: "ar",
              },
              {
                "@context": "https://schema.org",
                "@type": "Store",
                name: SITE_NAME,
                url: SITE_URL,
                address: {
                  "@type": "PostalAddress",
                  addressCountry: "YE",
                  addressLocality: "Yemen",
                },
                priceRange: "$$",
              },
            ]),
          }}
        />
        {/* Prevent FOUC: apply dark class before React hydrates */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='dark'||(!t&&window.matchMedia('(prefers-color-scheme:dark)').matches)){document.documentElement.classList.add('dark')}}catch(e){}})()`,
          }}
        />
      </head>
      <body
        className={`${cairo.variable} font-sans antialiased bg-background text-foreground`}
      >
        <ThemeProvider>
          <ErrorBoundary>
            <LayoutClient>
              {children}
            </LayoutClient>
          </ErrorBoundary>
          <Toaster />
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
